language: python

python:
  - "2.7"

before_install:
  - pip install tensorflow Cython contextlib2 pillow lxml jupyter matplotlib
  - git clone https://github.com/tensorflow/models.git
  - git clone https://github.com/cocodataset/cocoapi.git
  - cd cocoapi/PythonAPI
  - make
  - cp -r pycocotools ../../models/research/
  - cd ../../models/research
  - wget -O protobuf.zip https://github.com/google/protobuf/releases/download/v3.0.0/protoc-3.0.0-linux-x86_64.zip
  - unzip protobuf.zip
  - ./bin/protoc object_detection/protos/*.proto --python_out=.
  - export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim
  - cd ../..
  - sudo apt-get install -y libasound2-dev libjack-dev timidity alsa-base alsa-utils
  - sudo chmod a+wr /dev/dsp
  - sudo chmod a+wr /dev/audio*
  - sudo chmod a+wr /dev/mixer*
  - sudo chmod a+wr /dev/snd/seq*

install:
  - pip install -r requirements.txt

script:
  - pytest test/full_test.py test/playback_test.py
