language: python

python:
  - "2.7"

before_install:
  - sudo apt-get install libprotobuf-compiler -y
  - pip install tensorflow Cython contextlib2 pillow lxml jupyter matplotlib
  - git clone https://github.com/tensorflow/models.git
  - git clone https://github.com/cocodataset/cocoapi.git
  - cd cocoapi/PythonAPI
  - make
  - cp -r pycocotools ../../models/research/
  - cd ../../models/research
  - protoc object_detection/protos/*.proto --python_out=.
  - export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim
  - cd ../..

install:
  - pip install -r requirements.txt

script:
  - test/full_test.py